namespace Ecommerce.Core.Enums.Files
{
    public enum FileExtensionEnum
    {
        //Txt = 1,
        //Pdf = 2,
        //Doc = 3,
        //Docx = 4,
        //Xls = 5,
        //Xlsx = 6,
        //Png = 7,
        //Jpg = 8,
        //Jpeg = 9,
        //Gif = 10,
        //Csv = 11,
        //Svg = 12,
        //Jfif = 13,
        //Avif = 14,
        //Webp = 15,
        ////Tiff = 16,
        //Bmp = 17,
        //Cod = 18,
        //Ief = 19,
        //Jpe = 20,
        //Tif = 21,
        //Ras = 22,
        //Cmx = 23,
        //Pnm = 24,
        //Pbm = 25,
        //Pgm = 26,
        //Ppm = 27,
        //Rgb = 28,
        //Xbm = 29,
        //Xpm = 30,
        //Xwd = 31,
        //Nor = 32,
        //Mp4 =33,
        //mov = 34,

        Txt = 1,
        Pdf = 2,
        Doc = 3,
        Docx = 4,
        Xls = 5,
        Xlsx = 6,
        Png = 7,
        Jpg = 8,
        Jpeg = 9,
        Gif = 10,
        Csv = 11,
        Svg = 12,
        Jfif = 13,
        Avif = 14,
        Webp = 15,
        //Tiff = 16, (You commented this out, feel free to enable it)
        Bmp = 17,
        Cod = 18,
        Ief = 19,
        Jpe = 20,
        Tif = 21,
        Ras = 22,
        Cmx = 23,
        Pnm = 24,
        Pbm = 25,
        Pgm = 26,
        Ppm = 27,
        Rgb = 28,
        Xbm = 29,
        Xpm = 30,
        Xwd = 31,
        Nor = 32,

        // Adding common video formats
        mp4 = 33,
        Mov = 34,
        Avi = 35,
        Mkv = 36,
        Flv = 37,
        Wmv = 38,
        Webm = 39,
        M4v = 40,
        ThreeGp = 41,
        ThreeG2 = 42,
        Mpeg = 43,
        Mpg = 44,
        Rm = 45,
        Vob = 46,
        Ogv = 47,
        Asf = 48,
        Swf = 49,
        Mts = 50,
        M2ts = 51,
        F4v = 52,
        Divx = 53,
        Mxf = 54,
        Ts = 55,
        Dv = 56,
        H264 = 57,
        Hevc = 58,
        Vp9 = 59,
        Avchd = 60,
        Xvid = 61,


    }
}
